version: '3'
services:
  barotrauma:
    image: ghcr.io/f0rkz/docker-barotrauma:latest
    env_file: .env
    volumes:
      - ./local:/home/steam/.local
      - ./data:/data
      - ./clientpermissions.xml:/home/steam/clientpermissions.xml
    ports:
      - 27015:27015/udp
      - 27016:27016/udp
